name: Update Schedule
on:
  schedule:
    - cron: '0 0 * * *' # 毎日自動更新
  workflow_dispatch:     # 手動実行ボタン用

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Fetch and Save Data
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          # APIから直接データを取得
          curl -L -f -o schedule.json \
          -G "https://sofascore5.p.rapidapi.com/api/v1/unique-tournament/242/season/86668/events" \
          -H "x-rapidapi-key: $RAPIDAPI_KEY" \
          -H "x-rapidapi-host: sofascore5.p.rapidapi.com"
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add schedule.json
          git commit -m "Update match schedule" || exit 0
          git push
